"""Initial migration

Revision ID: e39908ae176b
Revises: 
Create Date: 2022-12-30 21:12:44.588096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39908ae176b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movieTable',
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('duration', sa.String(length=8), nullable=True),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('movieId')
    )
    with op.batch_alter_table('movieTable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movieTable_title'), ['title'], unique=True)

    op.create_table('userTable',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=25), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('emailAddress', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    with op.batch_alter_table('userTable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userTable_username'), ['username'], unique=True)

    op.create_table('watchedTable',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movieTable.movieId'], ),
    sa.ForeignKeyConstraint(['userId'], ['userTable.userId'], ),
    sa.PrimaryKeyConstraint('userId', 'movieId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchedTable')
    with op.batch_alter_table('userTable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userTable_username'))

    op.drop_table('userTable')
    with op.batch_alter_table('movieTable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movieTable_title'))

    op.drop_table('movieTable')
    # ### end Alembic commands ###
